# Gemfile for Microservice API
source 'https://rubygems.org'

ruby '3.1.0'

# Web framework
gem 'sinatra', '~> 3.0'

# Database
gem 'sequel', '~> 5.0'
gem 'sqlite3', '~> 1.5'
gem 'pg', '~> 1.4' # PostgreSQL driver

# Caching
gem 'redis', '~> 5.0'

# JSON handling
gem 'json', '~> 2.6'

# HTTP client
gem 'httparty', '~> 0.21'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.0'
  gem 'factory_bot', '~> 6.2'
  gem 'rubocop', '~> 1.50'
end

group :production do
  gem 'puma', '~> 6.0'
end
